-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 18:28:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plantX
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plantX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plantX` DEFAULT CHARACTER SET utf8 ;
USE `plantX` ;

-- -----------------------------------------------------
-- Table `plantX`.`plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plantX`.`plantas` ;

CREATE TABLE IF NOT EXISTS `plantX`.`plantas` (
  `idplantas` INT NOT NULL AUTO_INCREMENT,
  `nombre_planta` VARCHAR(45) NOT NULL,
  `temperatura_nocturna` INT NOT NULL,
  `temperatura_diurna` INT NOT NULL,
  `humedad` TINYINT NOT NULL,
  `luz_diaria` TINYINT NOT NULL,
  PRIMARY KEY (`idplantas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantX`.`raspberry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plantX`.`raspberry` ;

CREATE TABLE IF NOT EXISTS `plantX`.`raspberry` (
  `idraspberry` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `humedad_aire` TINYINT NOT NULL,
  `humedad_tierra` TINYINT NOT NULL,
  `lluvia` TINYINT NOT NULL,
  `luz` TINYINT NOT NULL,
  `temperatura` INT NOT NULL,
  `plantas_idplantas` INT NOT NULL,
  PRIMARY KEY (`idraspberry`),
  INDEX `fk_raspberry_plantas_idx` (`plantas_idplantas` ASC),
  CONSTRAINT `fk_raspberry_plantas`
    FOREIGN KEY (`plantas_idplantas`)
    REFERENCES `plantX`.`plantas` (`idplantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
